name: run hello-world from py script
on: push

jobs:
 hello:
   runs-on: ubuntu-latest

    steps:
    - name: clone repo
      uses: action/checkout@v3

    -name: setup python
     uses: action/setup-python@4
      with:
        python-version: '3.10'
    
    -name: run a py script
     run: python hello.py
        
